export const CALCULATE = 'CALCULATE';
export const CLEAR_DATA = 'CLEAR_DATA';
export const SAVE_DATA = 'SEND_DATA';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHANGE_MAIL = 'CHANGE_MAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SWITCH_AUTH_MODE = 'SWITCH_AUTH_MODE';

export const SEND_HEALTH_DATA = 'SEND_HEALTH_DATA';
export const SEND_HEALTH_DATA_START = 'SEND_HEALTH_DATA_START';
export const SEND_HEALTH_DATA_SUCCESS = 'SEND_HEALTH_DATA_SUCCESS';
export const SEND_HEALTH_DATA_FAIL = 'SEND_HEALTH_DATA_FAIL';
export const GET_MORE = 'GET_MORE';

export const FETCH_HEALTH_DATA = 'FETCH_HEALTH_DATA';
export const FETCH_HEALTH_DATA_START = 'FETCH_HEALTH_DATA_START';
export const FETCH_HEALTH_DATA_SUCCESS = 'FETCH_HEALTH_DATA_SUCCESS';
export const FETCH_HEALTH_DATA_FAIL = 'FETCH_HEALTH_DATA_FAIL';

export const CHANGE_HEALTH_DATA = 'CHANGE_HEALTH_DATA';

export const UPDATE_HEALTH_DATA = 'UPDATE_HEALTH_DATA';
export const UPDATE_HEALTH_DATA_START = 'UPDATE_HEALTH_DATA_START';
export const UPDATE_HEALTH_DATA_SUCCESS = 'UPDATE_HEALTH_DATA_SUCCESS';
export const UPDATE_HEALTH_DATA_FAIL = 'UPDATE_HEALTH_DATA_FAIL';

export const CHANGE_CARBS = 'CHANGE_CARBS';
export const CHANGE_PROTEIN = 'CHANGE_PROTEIN';
export const CHANGE_FAT = 'CHANGE_FAT';

export const SAVE_ASSUMPTIONS_DATA = 'SAVE_ASSUMPTIONS_DATA';
export const CHANGE_MEALS = 'CHANGE_MEALS';

export const SHOW_SIDE_DRAWER = 'SHOW_SIDE_DRAWER';
export const CLOSE_LOADING_MODAL = 'CLOSE_LOADING_MODAL';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';